export const FETCH_TODO_LIST = 'FETCH_TODO_LIST';
export const DELETE_THE_TODO = 'DELETE_THE_TODO';
export const CHANGE_THE_TODO = 'CHANGE_THE_TODO';
export const CREATE_A_NEW_TODO = 'CREATE_A_NEW_TODO';
